### PR TITLE
First pass at implementing wireframes

### PR DESCRIPTION
**Pull request by benheb**
Also adds: 
* Click state search 
* Bootstrap icons 
* Ability to close list view 
* Responsive CSS 

State view: 
open_fda

Detail view: 
open_fda

Mobile (responsive): 
open_fda

### CODE REVIEW

**Comment by ajturner** [comment]
what does the landing page look like on mobile responsive?

**Comment by benheb** [comment]
@ajturner I just hide the list for now, just see map.

**Comment by ajturner** [comment]
@benheb does that match the mock?

**Comment by benheb** [comment]
@ajturner I haven't seen a mobile mock for the landing page. The mock for landing page is just plan map of states, un-styled.

**Pull request merged**
