### PR TITLE
adding great arcs for source states

### PR DESCRIPTION
**Pull request by benheb**
* A few UI changes, mainly around continuing to work to clean up the lists.
* Changed map styling to remove initial choropleth map on load, and replace with light white states, and gray/blue selected states. 
* Idea for showing source states for recalls 

Home screen: 
open_fda

Select state: 
open_fda_and_dc__irc_esri_com_

Hovering over an item in list shows source state, and all other states impacted by recall: 
open_fda

@ajturner @michaelgaigg What do you think?

### CODE REVIEW

**Comment by chelm** [comment]
chelm says: "it's so hawt!!"

**Comment by gclancy** [comment]
Initial map 
- no city names, just state codes.
- Like the use of color on choropleth
- need dates of some sort (June 2012-May 2015) or what ever it is...perhaps put it under the title on teh right side popup

2nd map
- zoomed in on Texas?

3rd map 
- like the Red/Green higlights
- perhaps sort returned list with Ongoing ones on top of list...
- the lines are to the center point for the states affected?

**Comment by benheb** [comment]
@gclancy thanks for the feedback – 

Initial map
* What do you mean by no city names just state codes? 
* Agreed on adding dates, will work to add that in, and see what that looks like when we get final data source behind this 

2nd map 
* I was zooming, but then thought with showing source states, maybe stay zoomed out. Something to play with UX/functionality there, agreed. 

3rd map
* Good idea on sorting, will wait to see what the data looks like coming from koop, hopefully our wrapper can grab newest results first? I can also sort.
* Lines are to center of states affected, yes

**Comment by michaelgaigg** [comment]
#1
- Gerry probably means to hide the reference labels of the basemap and only show state abbreviations  instead (that's what I would like to see)
- I love the legend and its placement, absolutely necessary to have a legend!

#2
- Avoid zooming, there is no benefit really. Definitely highlight the state with a neutral color (e.g. blue) or if all the other states are being removed already with the initial classification color (even thought that might be blank, so maybe not

#3
- I would still like to see a filter there to sort on status (the tabs filter on class); also would love to see a filter by date if that even makes sense based on the data available (last year, last month,...)
- I absolutely love the affected states lines; now I also understand why the remaining states were removed (to avoid clutter). The sheer amount of lines gives me a visual indication of the impact

**Comment by ajturner** [comment]
@michaelgaigg are those blockers to this version or can those be follow-on stories in the backlog?

**Comment by benheb** [comment]
@michaelgaigg @gclancy I've removed city labels, but not sure where a state abbreviation layer is. I was just using `L.esri.basemapLayer("GrayLabels").addTo(this.map);` for the labels, and not seeing other options for abbr. Here's how it looks now without city labels. 

open_fda

@michaelgaigg @ajturner I'm not sure what you're referring to that would be 'blocking' – the filtering? If so, I think we do that in a future PR. I haven't forgotten about that, but sort of waiting for the Koop wrapper before I start tying into things like filtering. To me, this PR should stand on it's own.

**Comment by ajturner** [comment]
Merging this version - @michaelgaigg and @gclancy can add follow on user stories.

**Comment by ajturner** [comment]
Merging this version - @michaelgaigg and @gclancy can add follow on user stories.

**Comment by jodimward** [comment]
@benheb - this looks great! Dr. Bob will really like this - especially the functionality to see source location and distribution track. Good stuff!!!

**Pull request merged**
